---
# Deploy OWASP Hackademic
# https://github.com/Hackademic/hackademic
- name: Install git
  yum: name=git state=latest

- name: Clone hackademic repo
  git: >
    repo=https://github.com/Hackademic/hackademic.git
    dest={{ public_dir }}/hackademic
    force=yes

- name: chown hackademic
  file: >
    path={{ public_dir }}/hackademic
    owner=apache
    group=apache
    recurse=yes