---
# Deploy vulnerable apps
- name: Create apps dir
  file: >
    path={{ public_dir }}/vulnerable
    state=directory
    owner=apache
    group=apache
    mode=0755

- name: Deploy apps
  copy: >
    src={{ item }}.php
    dest={{ public_dir }}/vulnerable/{{ item }}.php
    owner=apache
    group=apache
    mode=0644
  with_items:
  - xss
  - traversal
  - sqli