---
- name: Install EPEL release
  yum: name=epel-release state=latest

- name: Install LAMP packages
  yum: state=latest name={{ item }}
  with_items:
    - mariadb-server
    - mariadb
    - httpd
    - php
    - php-mysql
    - MySQL-python
    - php-gd
    - php-odbc
    - php-pear
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - curl
    - curl-devel

- name: Start services
  service: name={{item}} state=started enabled=yes
  with_items:
    - mariadb
    - httpd

- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: >
    src=my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=0600

- name: Start services
  service: name=mariadb state=restarted