- name: Install Jenkins repo
  get_url: >
    url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest=/etc/yum.repos.d/jenkins.repo

- name: Install Jenkins repo key
  command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Java and jenkins
  yum: name={{ item }} state=latest
  with_items:
    - java
    - jenkins

- name: Start services
  service: name=jenkins state=restarted enabled=yes

# http://vm-jenkins.owasp.eee:8080