---
- hosts: vm-docker.owasp.demo
  sudo: yes
  roles:
  - roles/docker_host

- hosts: vm-jenkins.owasp.demo
  sudo: yes
  roles:
  - roles/docker_host

- hosts: vm-gocd.owasp.demo
  sudo: yes
  roles:
  - roles/docker_host

- hosts: vm-prod.owasp.demo
  sudo: yes
  roles:
  - roles/docker_host